### ISSUE TITLE
IndexOutOfBoundsException when using old console

### ISSUE THREAD

**Issue by nielsm5** [ibissource/ibis-ladybug#63] opened 2021-04-01 07:31 UTC
Tested with version 2.0.15-20210106.180557. See 
[ladybug-stracktrace.txt](https://github.com/ibissource/ibis-ladybug/files/6241770/ladybug-stracktrace.txt)

**Comment by jacodg** [comment] 2021-04-06 09:31
I think this is a duplicate of https://github.com/ibissource/ibis-ladybug/issues/60 which has been fixed, can you test/confirm?

**Comment by jacodg** [comment] 2021-06-04 15:58
Is indeed fixed according to Niels

**Closed by jacodg** 2021-06-04 15:58 UTC
